# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f547f7e468e7ed0bfeddb20947b796c157f67ebf6d9ca6f19bbbb8d525151804bc4cf5aa1522154f9b20fa9907aad605fd5227db4b5268bf37861edeb4d9e11

test:
  secret_key_base: 0cd54c70e7d6099c86487b19754280ab93e4c15d516b7bf6945152b84bd77cc112a1f3b7e9c1141f73fa9327186c18e943b8bdd4285fce1e3d8472d19f1e72bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
